language: objective-c
osx_image: xcode7
before_install:
  - gem install xcpretty
install: true
script:
  - set -o pipefail
  - xcodebuild -project GSAdditions.xcodeproj -scheme GSAdditions -destination 'platform=iOS Simulator,name=iPhone 6s' -sdk iphonesimulator test | xcpretty -c
