language: objective-c
osx_image: xcode7.3
before_install:
  - gem install xcpretty
before_script:
  - set -o pipefail
script:
  - xcodebuild -project GSAdditions.xcodeproj -scheme GSAdditions -destination 'platform=iOS Simulator,name=iPhone 6s' -sdk iphonesimulator test | xcpretty -c
notifications:
  slack:
    secure: OIAGlokV1kXCUfMfCe/O+kracXOl7DZf2ujToG152QR1kKp1GkNEiz/pNm3iE5AiOYxqKUViM5A62gU6yCEPdinE2m8jtxeBJe845l7+QKvm6cqhWqugO+Tko5PLny/cJ34Hu6oflOwysqVnd0frjktQgZSfWl6lGv3a5BahrAA=
